name: Docker app build

on: [push]

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build my app
        run: |
         docker build ./myapp -t myapp:1.0.0
    
